rep_app/urls.py
from rep_app import views
from django.urls import path

app_name = 'rep_app'

urlpatterns = [
    path(
        '',
        views.home_view,
        name='home_page'
    ),
    path(
        'reviews/',
        views.reviews_view,
        name='reviews'
    ),
    path(
        'scores/',
        views.scores_view,
        name='scores'
    ),
    path(
        'test/',
        views.test_view,
        name='test_view'
    ),
    path(
        'review/<int:pk>/',
        views.ReviewDetailView.as_view(),
        name='review_detail',
    ),
    path(
        'review/<int:review_id>/',
        views.reviews_view,
        name='review'
    ),
    path(
        'submit_review/<int:review_id>/',
        views.submit_review,
        name='submit_review'
    ),
    path(
        'tag_review/<int:review_id>/',
        views.tag_review,
        name='tag_review'
    ),
    path(
        'update_note/<int:note_id>/',
        views.update_note,
        name='update_note'
    ),
    path(
        'nudge/',
        views.nudge_view,
        name='nudge'
    ),
]

rep_project/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from rep_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'', include('rep_app.urls', namespace='rep_app')),
    re_path(r'login/',views.user_login,name='user_login'),
    re_path(r'logout/$',views.user_logout,name='logout'),
]

rep_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

from statistics import mean
from collections import Counter
from datetime import date, time, datetime, timedelta

def monday(date):
    return date - timedelta(date.weekday())

def weeks_ago(date, n):
    return date - timedelta(7*n)

def months_ago(date, n):
    return date - timedelta(28*n)

def one_year_ago(date):
    return date - timedelta(364)

today = date.today()
monday_this = monday(today)
monday_last = weeks_ago(monday_this, 1)
monday_last_month = months_ago(monday_this, 1)

# Create your models here.

class Manager(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return  self.user.first_name + ' ' + self.user.last_name

class OpsDirector(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return  self.user.first_name + ' ' + self.user.last_name

class Restaurant(models.Model):

    name = models.CharField(max_length=30)
    opsdirector = models.ForeignKey(OpsDirector, on_delete=models.CASCADE)
    manager = models.ForeignKey(Manager, on_delete=models.CASCADE, default=1)

    score_categories = ['total','food','service','ambience','value']
    date_strings = [period + '_' + duration if period == 'last' else period + '_' + duration + 's' for duration in ['week', 'month'] for period in ['last','two','three','four']]

    def __str__(self):
        return str(self.name)

    def my_mean(self, values):
        return round(mean(values),1) if values else 0

    def my_divide(self, x,y):
        return x/y if y != 0 else 0

    def get_last_week_reviews(self):
        return Review.objects.filter(
            restaurant=self.id,
            date__gte = monday_last,
            date__lt = monday_this
        ).order_by('score')

    def get_last_week_unsubmitted_reviews(self):
        return self.get_last_week_reviews().filter(
            reviewed = False,
            score__lt = 4
        ).order_by('score')

    def get_last_week_untagged_reviews(self):
        return self.get_last_week_reviews().filter(
            tagged = False,
            score__lt = 4
        ).order_by('score')[:100]

    def get_reviews_by_date(self, greater_than_equal_date,less_than_date):
        return Review.objects.filter(restaurant=self.id, date__gte = greater_than_equal_date, date__lt = less_than_date)

    def get_reviews_dict(self, reviews):

        return [
            {
                'total':getattr(review,'score'),
                'food':getattr(review,'food'),
                'service':getattr(review,'service'),
                'value':getattr(review,'value'),
                'ambience':getattr(review,'ambience'),
                'submitted':getattr(review, 'reviewed')
            } for review in reviews
        ]

    def get_scores_dict(self, reviews):

        reviews_dict = self.get_reviews_dict(reviews)

        return {
            category: {
                'total': len([review[category] for review in reviews_dict if review[category] > 0]),
                'average': self.my_mean([review[category] for review in reviews_dict if review[category] > 0])
            } for category in self.score_categories
        }

    def get_stats(self):

        reviews = self.get_last_week_reviews()
        reviews_dict = self.get_reviews_dict(reviews)

        return {
            'scores': {
                category:{
                    'total': len([review[category] for review in reviews_dict if review[category] > 0]),
                    'average': self.my_mean([review[category] for review in reviews_dict if  review[category] > 0])
                } for category in self.score_categories
            },
            'submissions': {
                'submitted_reviews': len([review['total'] for review in reviews_dict if review['submitted'] and review['total'] < 4]),
                'unsubmitted_reviews': len([review['total'] for review in reviews_dict if not review['submitted'] and review['total'] < 4]),
                'submitted_p': round(self.my_divide(len([review['total'] for review in reviews_dict if review['submitted'] and review['total'] < 4]), len([review['total'] for review in reviews_dict if review['total'] < 4]))*100)
            },
            'below_4': {
                'reviews_below_4': len([review['total'] for review in reviews_dict if review['total'] < 4]),
                'reviews_below_4_p': round(self.my_divide(len([review['total'] for review in reviews_dict if review['total'] < 4]), len([review['total'] for review in reviews_dict]))*100),
            }
        }

    def get_scores(self):

        weeks_scores = [self.get_scores_dict(self.get_reviews_by_date(weeks_ago(monday_last,i), weeks_ago(monday_this,i))) for i in range(4)]
        months_scores = [self.get_scores_dict(self.get_reviews_by_date(months_ago(monday_last_month, i),months_ago(monday_this,i))) for i in range(4)]
        all_scores = weeks_scores + months_scores

        scores_dict = {self.date_strings[i]:all_scores[i] for i in range(8)}

        return {
            category.capitalize():{
                date_string:{
                    'reviews':scores_dict[date_string][category.lower()]['total'],
                    'score':scores_dict[date_string][category.lower()]['average']
                } for date_string in self.date_strings
            } for category in self.score_categories
        }

    def get_tag_counts(self, reviews):

        tag_lists = [review.get_tag_list() for review in reviews]
        all_tags = [tag for tag_list in tag_lists for tag in tag_list]
        tags_counter = Counter(all_tags)
        tag_counts = {tag:count for tag,count in tags_counter.items()}

        return tag_counts

    def get_tags(self):

        return self.get_tag_counts(self.get_last_week_reviews())


class Tag(models.Model):

    text = models.CharField(max_length=100)
    display_text = models.CharField(max_length=100, default='')

    def __str__(self):
        return str(self.text)

class Review(models.Model):

    source = models.CharField(max_length=11)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, default='')
    date = models.DateField()
    visit_date = models.CharField(max_length=20, null=True)
    score = models.IntegerField()
    food = models.IntegerField(null=True)
    service = models.IntegerField(null=True)
    value = models.IntegerField(null=True)
    ambience = models.IntegerField(null=True)
    text = models.TextField(max_length=10000, null=True)
    link = models.TextField(max_length=300, null=True)
    tags = models.ManyToManyField(Tag, null=True)
    comment = models.TextField(max_length=10000, null=True)
    replied = models.BooleanField(default=False)
    reviewed = models.BooleanField(default=False)
    tagged = models.BooleanField(default=False, null=True)

    def __str__(self):
        return str(self.title)

    def get_absolute_url(self):
        return reverse("rep_app:review_detail",kwargs={'pk':self.pk})

    def get_tag_list(self):
        return [tag.display_text for tag in self.tags.all()]

class Note(models.Model):

    restaurant = models.OneToOneField(Restaurant, on_delete=models.CASCADE)
    text = models.TextField(max_length=1000, default='')

    def __str__(self):
        return str(self.restaurant)





# class Comment(models.Model):
#
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     review = models.ForeignKey(Review, on_delete=models.CASCADE)
#     date = models.DateTimeField(auto_now_add=True)
#     text = models.TextField(max_length=1000)
#
#     def get_absolute_url(self):
#         return reverse("rep_app:review_detail",kwargs={'pk':self.review_id})

rep_app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse, reverse_lazy
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView

from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required

from django.core.exceptions import ObjectDoesNotExist
from django.core.mail import send_mail

from rep_app.models import Manager, OpsDirector, Restaurant, Review, Note, Tag
from rep_app.emails import AppEmail, NoteNotification, NudgeNotification, SubmittedNotification, ReviewsNotification

from datetime import date, time, datetime, timedelta

# Date Variables

today = date.today()
monday_this = today - timedelta(today.weekday())
monday_last = monday_this - timedelta(7)

# App URL

app_url = 'http://127.0.0.1:8000/'

# Filtering functions

def filter_restaurants(request):

    try:
        restaurants = request.user.manager.restaurant_set.all()
    except ObjectDoesNotExist:
        try:
            restaurants = request.user.opsdirector.restaurant_set.all()
        except:
            restaurants = Restaurant.objects.all()

    return restaurants

def filter_reviews_by_restaurant(request,reviews):

    try:
        reviews = reviews.filter(restaurant = request.user.manager.restaurant_set.first())
    except ObjectDoesNotExist:
        try:
            reviews = reviews.filter(restaurant__in = request.user.opsdirector.restaurant_set.all())
        except ObjectDoesNotExist:
            pass

    return reviews

def filter_reviews_by_submitted(request,reviews):

    try:
        request.user.manager
        reviews = reviews.filter(reviewed = False)
    except ObjectDoesNotExist:
        if request.user.is_staff:
            reviews = reviews.filter(reviewed = False)
        else:
            pass

    return reviews

def filter_reviews_by_text(reviews):

    return reviews.exclude(text = '')


# Create your views here.

def test_view(request):

    restaurants = Restaurant.objects.all()
    context = {'restaurants':restaurants}

    # reviews = Review.objects.filter(date__gte=today)
    # context = {'reviews':reviews}

    # notes = Note.objects.all()
    # context = {'restaurants':restaurants}

    return render(request, 'rep_app/test.html', context)

@login_required
def home_view(request):

    reviews = Review.objects.filter(
        date__gte = monday_this,
        score__lt = 4,
        tagged = False,
    ).order_by('score', 'restaurant')

    restaurants = filter_restaurants(request)
    reviews = filter_reviews_by_restaurant(request,reviews)
    reviews = filter_reviews_by_submitted(request,reviews)
    reviews = filter_reviews_by_text(reviews)
    tags = Tag.objects.all().order_by('text')

    reviews = reviews[:100]

    context = {
        'restaurants':restaurants,
        'reviews':reviews,
        'tags':tags
    }

    try:
        request.user.manager
    except ObjectDoesNotExist:
        try:
            request.user.opsdirector
        except ObjectDoesNotExist:
            if not request.user.is_staff:
                context = {'restaurants':restaurants}

    return render(request, 'rep_app/home_page.html', context)

@login_required
def reviews_view(request):

    reviews = Review.objects.filter(
        date__lt = monday_this,
        date__gte = monday_last
    ).order_by('score', 'restaurant')

    restaurants = filter_restaurants(request)
    reviews = filter_reviews_by_restaurant(request,reviews)
    tags = Tag.objects.all().order_by('text')

    context = {
        'reviews':reviews,
        'restaurants':restaurants,
        'tags':tags
    }

    return render(request, 'rep_app/reviews.html', context)

@login_required
def scores_view(request):

    restaurants = filter_restaurants(request)

    context = {'restaurants':restaurants}

    return render(request, 'rep_app/scores.html', context)

@login_required
def tag_review(request, review_id):

    if request.method == "POST":

        review = get_object_or_404(Review, pk=review_id)
        tag_objects = Tag.objects.all()

        for tag_object in tag_objects:
            is_tag = request.POST.get(tag_object.text, False)
            if is_tag:
                review.tags.add(tag_object)
            else:
                review.tags.remove(tag_object)

        review.tagged = True
        review.save()

    return redirect('rep_app:review_detail', pk=review_id)

class ReviewDetailView(DetailView):
    model = Review

@login_required
def submit_review(request, review_id):

    if request.method == "POST":

        review = get_object_or_404(Review, pk=review_id)
        review.comment = request.POST['comment']
        review.reviewed = True
        review.save()

        ops_director = review.restaurant.opsdirector
        no_of_unsubmitted_reviews = sum([len(restaurant.get_last_week_unsubmitted_reviews()) for restaurant in ops_director.restaurant_set.all()])

        if no_of_unsubmitted_reviews == 0:

            subject = 'Your reviews have been submitted'
            recipient = 'domgunewardena@gmail.com'
            email_text = SubmittedNotification(ops_director.user.first_name, app_url)
            html = email_text.html
            text = email_text.text

            email = AppEmail(subject, recipient, html, text)
            email.send()

        no_of_unsubmitted_reviews = sum([len(restaurant.get_last_week_unsubmitted_reviews()) for restaurant in Restaurant.objects.all()])

        if no_of_unsubmitted_reviews == 0:

            subject = 'All reviews have been submitted'
            recipient = 'domgunewardena@gmail.com'
            email_text = SubmittedNotification('Annabel', app_url)
            html = email_text.html
            text = email_text.text

            email = AppEmail(subject, recipient, html, text)
            email.send()

    return redirect('rep_app:home_page')

@login_required
def update_note(request, note_id):

    if request.method == "POST":

        note = get_object_or_404(Note, pk=note_id)
        note.text = request.POST['note']
        note.save()

        if request.POST['note'] != '':

            manager = note.restaurant.manager.user.first_name
            restaurant = note.restaurant.name

            subject = restaurant + ' has a new note'
            # recipient = 'domgunewardena@gmail.com'
            recipient = 'annabels@danddlondon.com'
            email_text = NoteNotification(restaurant, manager, note.text, app_url)
            html = email_text.html
            text = email_text.text

            email = AppEmail(subject, recipient, html, text)
            email.send()

    return redirect('rep_app:reviews')

@login_required
def nudge_view(request):

    restaurants = Restaurant.objects.all()

    for restaurant in restaurants:

        if len(restaurant.get_last_week_unsubmitted_reviews()) > 0:

            restaurant_name = restaurant.name
            manager = restaurant.manager.user.first_name

            subject = 'Annabel has nudged you'
            # recipient = 'domgunewardena@gmail.com'
            recipient = 'annabels@danddlondon.com'
            email_text = NudgeNotification(restaurant_name, manager, app_url)
            html = email_text.html
            text = email_text.text

            email = AppEmail(subject, recipient, html, text)
            email.send()

    return redirect('home_page')

# User Login Views

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('rep_app:home_page'))

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('rep_app:home_page'))

            else:
                return HttpReponse('ACCOUNT NOT ACTIVE')
        else:
            print('Someone tried to login and failed!')
            print('Username: {} and password {}'.format(username,password))
            return HttpResponse('Invalid login details supplied!')
    else:
        return render(request,'rep_app/login.html',{})

rep_app/templates/rep_app/login.html
{% extends 'rep_app/base.html' %}

{% block body_block %}

<div class="container">
  <div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% url 'user_login' %}" method="post">
      {% csrf_token %}
      <label for="username">Email:</label>
      <input type="text" name="username" placeholder="Username">
      <label for="password">Password:</label>
      <input type="password" name="password">
      <input type="submit" name="" value="Login">
    </form>
    <hr>


  </div>

</div>

{% endblock %}

rep_app/templates/rep_app/old_reviews_with_table.html
{% extends "rep_app/base.html" %}
{% block body_block %}

<!-- Restaurant Stats & Comments Table -->
{% if user.is_staff %}

<div class="jumbotron no-button-jumbotron">
  <div class="container">
    <p class = "lead">Here's the review breakdown plus the notes that the other users see - type in the boxes & click Update to change them! </p>
  </div>
</div>

<!-- Restaurant Stats & Notes Table -->

<!-- Filters  -->
<input id='breakdownFilter' type="text" style="width:100%;" placeholder="Filter by restaurant" class='table-filter' onkeyup='filterBreakdown()'>

<!-- Table -->
<table id = 'breakdownTable' class = 'breakdown-table note-table table table-hover' style="width:100%">
  <colgroup>
    <col span="1" style="width: 20%;">
    <col span="1" style="width: 5%;">
    <col span="1" style="width: 5%;">
    <col span="1" style="width: 5%;">
    <col span="1" style="width: 5%;">
    <col span="1" style="width: 5%;">
    <col span="1" style="width: 5%;">
    <col span="1" style="width: 5%;">
    <col span="1" style="width: 5%;">
    <col span="1" style="width: 35%;">
    <col span="1" style="width: 5%;">
  </colgroup>
  <thead class = "thead-dark">
    <tr>
      <th><p style = "text-align:left;">Restaurant</p></th>
      <th><p>Score</p></th>
      <th><p>Food</p></th>
      <th><p>Service</p></th>
      <th><p>Ambience</p></th>
      <th><p>Value</p></th>
      <th><p>Reviews</p></th>
      <th><p><4</p></th>
      <th><p>% <4</p></th>
      <th><p>Notes</p></th>
      <th><p></p></th>
    </tr>
  </thead>
  {% for restaurant,value_dicts in restaurant_stats.items %}
    {% if user.manager and user.manager.restaurant == restaurant or not user.manager %}
      <tr>
        <td><p style = "text-align:left;">{{restaurant}}</p></td>
        <!-- Loop through categories -->
        {% for category, values in value_dicts.scores.items %}
          {% if values.average == 0 %}
            {% if category == 'total' %}
              <td><p title = 'No guests left a review'>-</p></td>
            {% else %}
              <td><p title = 'No guests left a {{category}} score'>-</p></td>
            {% endif %}
          {% else %}
            {% if values.average > 4.5 %}
              <td class = "table-success">
            {% elif values.average > 4 %}
              <td class = "table-warning">
            {% elif values.average <= 4 %}
              <td class = "table-danger">
            {% endif %}
            <p onclick = "filterStat('{{restaurant}}', '{{category}}')" title = 'This score is the average from {{values.total}} reviews'>{{values.average}}</p></td>
          {% endif %}
        {% endfor %}

        <td><p>{{value_dicts.scores.total.total}}</p></td>
        <td><p title = "{{value_dicts.below_4.reviews_below_4}} reviews had 3 ★s or less">{{value_dicts.below_4.reviews_below_4}}</p></td>
        {% if value_dicts.below_4.reviews_below_4_p < 10 %}
          <td class = "table-success">
        {% else %}
          <td class = "table-danger">
        {% endif %}
          <p title = "{{value_dicts.below_4.reviews_below_4_p}}% of reviews had 3 ★s or less">{{value_dicts.below_4.reviews_below_4_p}}%</p></td>

        <!-- Notes Input -->
        {% for note in notes %}
          {% if note.restaurant == restaurant %}
            <form action = "{% url 'rep_app:update_note' note.id %}" method="post">
            {% csrf_token %}
              {% if note.text %}
                <td><input type='text' class='text-input' name="note" value = "{{note.text}}"></input></td>
              {% else %}
                <td><input type='text' class='text-input' name="note"></input></td>
              {% endif %}
            <td><button type="submit" class='btn btn-primary note-submit' name="Update" value="Update">Update</button></td>
            </form>
          {% endif %}
        {% endfor %}
      </tr>
      {% endif %}
    {% endfor %}
  </table>
<!-- End logic for showing notes table to staff -->
{% endif %}

<!-- Review List Jumbotron -->

<div class="jumbotron no-button-jumbotron">
  <div class="container">
    <p class = "lead">
      {% if user.manager %}
        Here are all {{user.manager.restaurant}}'s reviews from last week
      {% else %}
        Here are all the reviews from last week
      {% endif %}
    </p>
  </div>
</div>


<!-- List of Reviews -->

<!-- Filters -->

<div class="table-filter-inputs-div">
  <div class="table-filter-input-div" style = "width:27%">
    <select class = "form-select table-filter restaurant-dropdown" id="restaurantFilter" style = 'height:100%' name='restaurant' onchange='filterRestaurant(this.value)'>
      <option value="All Restaurants">All Restaurants</option>
      {% for restaurant in restaurant_list %}
        <option value="{{restaurant}}">{{restaurant}}</option>
      {% endfor %}
    </select>
  </div>
  <div class="table-filter-input-div" style = "width:60%">
    <input type="text" class="table-filter" id="reviewFilter" placeholder='Search reviews for keyword'>
  </div>
  <div class="table-filter-input-div" style = "height:100%">
    <input type="submit" class = "table-filter" value = '🔍' onclick="filterReview()" title='Filter reviews by search term'></input>
  </div>
  <div class="table-filter-input-div">
    <input type="submit" class = "table-filter" value = '✕' onclick="clearReviewFilter()" title='Clear search'></input>
  </div>
</div>

<!-- Reviews Table -->

<table id ='reviewsTable' class = 'reviews-table table table-hover' style="width: 100%">
<colgroup>
  <col span="1" style="width: 1%;">
  <col span="1" style="width: 13%;">
  <col span="1" style="width: 1%;">
  <col span="1" style="width: 1%;">
  <col span="1" style="width: 1%;">
  <col span="1" style="width: 1%;">
  <col span="1" style="width: 1%;">
  <col span="1" style="width: 38%;">
  <col span="1" style="width: 38%;">
  <col span="1" style="width: 5%;">
</colgroup>
<thead class = 'thead-dark'>
  <tr>
    <th><p></p></th>
    <th><p>Restaurant</p></th>
    <th><p title='Overall Score'>★</p></th>
    <th class='filter-column' onclick="clickFilterColumn(this,3,'number')"><p title='Click to only see reviews with a Food Score'>F</p></th>
    <th class='filter-column' onclick="clickFilterColumn(this,4,'number')"><p title='Click to only see reviews with a Service Score'>S</p></th>
    <th class='filter-column' onclick="clickFilterColumn(this,5,'number')"><p title='Click to only see reviews with an Ambience Score'>A</p></th>
    <th class='filter-column' onclick="clickFilterColumn(this,6,'number')"><p title='Click to only see reviews with a Value Score'>V</p></th>
    <th class='filter-column' onclick="clickFilterColumn(this,7,'text')"><p title='Click to only see reviews with a written review' style = "text-align:center;">Review</p></th>
    <th><p style = "text-align:center;">Comment</p></th>
    {% if not user.manager %}
      <th><p>Submitted</p></th>
    {% else %}
      <th><p></p></th>
    {% endif %}
  </tr>
</thead>
{% for review in reviews %}
    {% if review.score > 3 %}
      <tr class = "table-success">
    {% elif review.score == 3 %}
      <tr class = "table-warning">
    {% elif review.score < 3 %}
      <tr class = "table-danger">
    {% endif %}
      <td>
        {% if review.source == 'Google' %}
          {% load static %}
          <img src="{% static 'logos/google.png' %}" alt="Google Logo" title = 'This review was posted on Google'>
        {% elif review.source == 'Tripadvisor' %}
          {% load static %}
          <img src="{% static 'logos/tripadvisor.png' %}" alt="Tripadvisor Logo" title = 'This review was posted on Tripadvisor'>
        {% elif review.source == 'SevenRooms' %}
          {% load static %}
          <img src="{% static 'logos/sevenrooms.png' %}" alt="SevenRooms Logo" title = 'This review was posted on SevenRooms'>
        {% elif review.source == 'Opentable' %}
          {% load static %}
          <img src="{% static 'logos/opentable.png' %}" alt="Opentable Logo" title = 'This review was posted on Opentable'>
        {% else %}
          <p title = 'This review was posted on {{review.source}}'>{{review.source}}</p>
        {% endif %}
      </td>
      <td><p>{{review.restaurant}}</p></td>
      {% if review.score > 0 %}
        <td><p title='Overall Score'>{{review.score}}</p></td>
      {% else %}
        <td><p title='Overall Score'>-</p></td>
      {% endif %}
      {% if review.food > 0 %}
        <td><p title='Food Score'>{{review.food}}</p></td>
      {% else %}
        <td class='empty'><p title="This review doesn't have a Food Score">-</p></td>
      {% endif %}
      {% if review.service > 0 %}
        <td><p title='Service Score'>{{review.service}}</p></td>
      {% else %}
        <td class='empty'><p title="This review doesn't have a Service Score">-</p></td>
      {% endif %}
      {% if review.ambience > 0 %}
        <td><p title='Ambience Score'>{{review.ambience}}</p></td>
      {% else %}
        <td class='empty'><p title="This review doesn't have an Ambience Score">-</p></td>
      {% endif %}
      {% if review.value > 0 %}
        <td><p title='Value Score'>{{review.value}}</p></td>
      {% else %}
        <td class='empty'><p title="This review doesn't have a Value Score">-</p></td>
      {% endif %}
      {% if review.text == "nan" %}
        <td class='empty'><p title="This customer didn't leave a written review" class = 'empty-text'><i>This customer didn't write a review</i></p></td>
      {% else %}
        <td><p title="This is the review that the customer wrote">{{review.text}}</p></td>
      {% endif %}
      <!-- Display submit form to managers -->
      {% if user.manager %}
        <form action = "{% url 'rep_app:submit_review' review.id %}" method="post">
        {% csrf_token %}
          {% if review.comment %}
            <td><textarea class='text-input' name="comment" required>{{review.comment}}</textarea></td>
          {% else %}
            <td><textarea class='text-input' name="comment" required></textarea></td>
          {% endif %}
        <td><input type="submit" name="Submit" value="Submit"></td>
        </form>
      <!-- Display comment to staff/directors -->
      {% else %}
      <td>
        {% if review.comment %}
          <p title = 'This is the comment the manager has left'>{{review.comment}}</p>
        {% else %}
          <p title = "The manager hasn't left a comment yet" class = 'empty-text'>
          {% if review.score > 3 %}
            <i>Managers aren't required to leave comments on reviews with more than 3 ☆s</i>
          {% else %}
            <i>The manager hasn't left a comment yet</i>
          {% endif %}
          </p>
        {% endif %}
        </td>
        <td>
        {% if review.reviewed %}
          <p title = 'The manager has submitted this review' style = "text-align:center">✓</p>
        {% elif review.score < 4 %}
          <p title = "The manager hasn't submitted this review yet" style = "text-align:center">✕</p>
        {% endif %}
        </td>
      {% endif %}
    </tr>
  {% endfor %}
</table>

{% endblock %}

rep_app/templates/rep_app/review_detail.html
{% extends "rep_app/base.html" %}
{% block body_block %}
<h1>Hello</h1>
{% endblock %}